import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "@/app/styles/globals.scss";
import { notoSans } from "@/app/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { lang },
  children,
}: {
  children: React.ReactNode;
  params: { lang: "en" | "zh" };
}) {
  return (
    <html lang={lang === "en" ? "en" : "zh-tw"}>
      <body className={notoSans.className}>
        <Header />
        {children}
        <Footer lang={lang} />
      </body>
    </html>
  );
}
